/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_rousan_androidwithrust_bridge_Bridge */

#ifndef _Included_io_rousan_androidwithrust_bridge_Bridge
#define _Included_io_rousan_androidwithrust_bridge_Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_rousan_androidwithrust_bridge_Bridge
 * Method:    startNativeBridge
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_rousan_androidwithrust_bridge_Bridge_startNativeBridge
  (JNIEnv *, jobject);

/*
 * Class:     io_rousan_androidwithrust_bridge_Bridge
 * Method:    shutdownNativeBridge
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_rousan_androidwithrust_bridge_Bridge_shutdownNativeBridge
  (JNIEnv *, jobject);

/*
 * Class:     io_rousan_androidwithrust_bridge_Bridge
 * Method:    sendMessageToNativeBridge
 * Signature: (ILandroid/os/Bundle;)V
 */
JNIEXPORT void JNICALL Java_io_rousan_androidwithrust_bridge_Bridge_sendMessageToNativeBridge
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
