/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_rousan_androidwithrust_Runtime */

#ifndef _Included_io_rousan_androidwithrust_Runtime
#define _Included_io_rousan_androidwithrust_Runtime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_rousan_androidwithrust_Runtime
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_rousan_androidwithrust_Runtime_start
  (JNIEnv *, jobject);

/*
 * Class:     io_rousan_androidwithrust_Runtime
 * Method:    sendMessage
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_rousan_androidwithrust_Runtime_sendMessage
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     io_rousan_androidwithrust_Runtime
 * Method:    sendMessage2
 * Signature: (ILandroid/os/Bundle;)V
 */
JNIEXPORT void JNICALL Java_io_rousan_androidwithrust_Runtime_sendMessage2
  (JNIEnv *, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
