/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_rousan_androidwithrust_bridge_Bridge */

#ifndef _Included_io_rousan_androidwithrust_bridge_Bridge
#define _Included_io_rousan_androidwithrust_bridge_Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_rousan_androidwithrust_bridge_Bridge
 * Method:    initiateBridge
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_rousan_androidwithrust_bridge_Bridge_initiateBridge
  (JNIEnv *, jobject);

/*
 * Class:     io_rousan_androidwithrust_bridge_Bridge
 * Method:    emitEventToRust
 * Signature: (Ljava/lang/String;Landroid/os/Bundle;)V
 */
JNIEXPORT void JNICALL Java_io_rousan_androidwithrust_bridge_Bridge_emitEventToRust
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
